server:
  port: 8085

spring:
  datasource:
    username: root
    password: nQek0lJVDNe1pdCundVVf1cqFfDpzmpJ
    url: jdbc:postgresql://root:nQek0lJVDNe1pdCundVVf1cqFfDpzmpJ@dpg-cs1kmp88fa8c73d16ke0-a.oregon-postgres.render.com/bootstrapshop_7y3t
   
  #datasource:
   #username: root
   #password: password
   #url: jdbc:mysql://localhost:3306/bootstrapshop
  
  
    
    
  jpa:
    hibernate:
    #更新或創建數據表結構
      ddl-auto: update
    #控制台顯示sql
    show-sql: true
