server:
  port: 8085

spring:
  datasource:
    username: root
    password: gvCoJ1Lsw2KtZWCKUfJrNHPRKkzhywUL
    url: jdbc:postgresql://dpg-cl8pt62vokcc73b2ai10-a:5432/bootstrapshop
  jpa:
    hibernate:
    #更新或創建數據表結構
      ddl-auto: update
    #控制台顯示sql
    show-sql: true