server:
  port: 8085

spring:
  datasource:
    username: demosql_yj85_user
    password: xvhWaH5JU6J13VKNQxnydssLq2Ujjx12
    url: jdbc:postgresql://demosql_yj85_user:xvhWaH5JU6J13VKNQxnydssLq2Ujjx12@dpg-cugnb6bv2p9s73cl75og-a/demosql_yj85
    
  jpa:
    hibernate:
      ddl-auto: update  # 更新或創建數據表結構
    show-sql: true      # 控制台顯示 SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
   
  #datasource:
   #username: root
   #password: password
   #url: jdbc:mysql://localhost:3306/bootstrapshop
  
  
    

