server:
  port: 8085

spring:
  datasource:
    username: b0612ken_user
    password: zAbg57utxQe1f5NbDWye1hQvRaW0RCep
    url: jdbc:postgresql://b0612ken_user:zAbg57utxQe1f5NbDWye1hQvRaW0RCep@dpg-cs1kee88fa8c73d15ac0-a.oregon-postgres.render.com/b0612ken
   
  #datasource:
   #username: root
   #password: password
   #url: jdbc:mysql://localhost:3306/bootstrapshop
  
  
    
    
  jpa:
    hibernate:
    #更新或創建數據表結構
      ddl-auto: update
    #控制台顯示sql
    show-sql: true
